### ISSUE TITLE
手機版破版

### ISSUE THREAD

**Issue by wildskyf** [linux-taiwan/kde.linux.org.tw#8]
盲猜應該是 nav bar 爆了

**Comment by Brli** [comment]
請問手機的螢幕顯示尺寸？
可以附截圖嗎？

**Comment by wildskyf** [comment]
開瀏覽器的 responsive（320px） 就可以直接看到爆掉了

![2016-12-13 00 36 00](https://cloud.githubusercontent.com/assets/6042803/21107285/28a609f8-c0cc-11e6-8dfc-90892549e553.png)
![2016-12-13 00 35 51](https://cloud.githubusercontent.com/assets/6042803/21107286/28da8c32-c0cc-11e6-9b1b-3ae0ed64ee48.png)

**Comment by Brli** [comment]
這個 css 是 KDE 官方的版…他們似乎沒考慮到這麼小的螢幕寬度Orz

**Comment by s8321414** [comment]
這要怎麼 patch 啊 Orz

**Comment by Brli** [comment]
暫時先修成這樣，照理講應該用 @media(min width) 之類的東西，在某個尺度下以後改成顯示 tab button，但是我還不會使用這個魔法 ><
![screenshot_20161213_114645](https://cloud.githubusercontent.com/assets/4042566/21126860/e8658d2e-c129-11e6-85ca-12df205bff6d.png)
